### ISSUE TITLE
Display changes cause application to open off-screen

### ISSUE THREAD

**Issue by friksa** [Sethorax/electron-window-state-manager#1]
Thanks for a great project!

These are the steps to get the app to open “off-screen” and inaccessible:
1) Use the app in a Windows extended display system (with a second display), and close the app while it is on the second display
2) now disconnect the second display
3) reopen the app and it opens up offscreen

Basically you can’t get to the app until you can get back to the second display to move it to display 1. 

What is expected:
- on startup, the app should check all the available displays and make sure it is visible somewhere... otherwise, it should just reset to the center of the first display.

I know that this can be added outside of this module... but then each developer will have to do it and possibly getting it wrong.  If it is part of this module, then all apps using it will behave great!

**Comment by Sethorax** [comment]
Hello @friksa.

Thank you for your feedback.  
I updated the project and fixed the bug. It will now check the coordinates of the saved window and if the window would appear outside of the viewport, it will just center it on the primary display.

Please let me know, if you experience any more problems on a second monitor.

**Comment by friksa** [comment]
Looks like it is fixed.  Awesome job and thanks!!
