### ISSUE TITLE
support for productName field in package.json

### ISSUE THREAD

**Issue by hkuclion** [Sethorax/electron-window-state-manager#3]
there is a productName field in package.json, which if you set, will be the folder name in `userData`.
however, line 11 in WindowState.js
```js
const stateFile = path.join(utils.getAppDataPath(), utils.getManifestData().name, 'windowStates.json');
```
only use the name field, thus will use different folder than electron,
can it be `utils.getManifestData().productName || utils.getManifestData().name`

Update: use native `app.getName()` seems better, I had made an pull request;

**Comment by Sethorax** [comment]
I merged your pull request and adjusted the unit tests accordingly.
Thanks for your contribution.
